# Generated by Django 5.2.8 on 2025-11-17 16:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('neurology', 'Neurology'), ('gynecology', 'Gynecology'), ('psychiatry', 'Psychiatry'), ('dentistry', 'Dentistry'), ('ophthalmology', 'Ophthalmology'), ('general', 'General Medicine')], default='general', max_length=50)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('hospital', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('booking_option', models.CharField(choices=[('online', 'Online Only'), ('inperson', 'In-Person Only'), ('both', 'Both Online & In-Person')], default='both', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('online', 'Online Consultation'), ('inperson', 'In-Person Visit')], default='online', max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctor')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
