# Generated by Django 5.2.8 on 2025-11-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('online', 'Online Only'), ('inperson', 'In-Person Only'), ('both', 'Both Online & In-Person')], default='online', max_length=10),
        ),
    ]
