# Generated by Django 5.2.8 on 2025-11-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='booking_option',
        ),
    ]
