# Generated by Django 5.2.8 on 2025-11-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='patient', max_length=100),
            preserve_default=False,
        ),
    ]
